IMPORT JAVAX.SWING.JFRAME;

IMPORT COM.MXGRAPH.SWING.MXGRAPHCOMPONENT;
IMPORT COM.MXGRAPH.VIEW.MXGRAPH;

PUBLIC CLASS HABRGRAPH EXTENDS JFRAME {

    PUBLIC STATIC VOID MAIN(STRING[] ARGS) {
        HABRGRAPH FRAME = new HABRGRAPH();
        FRAME.SETDEFAULTCLOSEOPERATION(JFRAME.EXIT_ON_CLOSE);
        FRAME.SETSIZE(400, 320);
        FRAME.SETVISIBLE(TRUE);

    }

    PUBLIC HABRGRAPH()
    {
        SUPER("HABRAGRAPH");

        MXGRAPH GRAPH = new MXGRAPH();
        OBJECT PARENT = GRAPH.GETDEFAULTPARENT();

        GRAPH.GETMODEL().BEGINUPDATE();
        try
        {
            OBJECT v1 = GRAPH.INSERTVERTEX(PARENT, NULL, "HABRA", 20, 20, 80, 30);
            OBJECT v2 = GRAPH.INSERTVERTEX(PARENT, NULL, "Hab", 240, 150, 80, 30);
            GRAPH.INSERTEDGE(PARENT, NULL, "ДУГА", v1, v2) ;
        }
        FINALLY
        {
            GRAPH.GETMODEL().ENDUPDATE();
        }

        MXGRAPHCOMPONENT GRAPHCOMPONENT = new MXGRAPHCOMPONENT(GRAPH);
        GETCONTENTPANE().ADD(GRAPHCOMPONENT);
    }

}
